[package]
name = "gifteroids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: Trim down to necessary feature for small webapplication
bevy = "0.8.1"
rand = "0.8.0"

# TODO: Optimize for size when doing web output